name: 'Test'

on:
  push:
    branches: [ 'master' ]

jobs:
  unit-testing-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Get Repo Files
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install dependencies
        run: npm install --include=dev

      - name: Build
        run: npm run compile

      - name: Testing
        run: npm test